# Generated by Django 4.2 on 2024-05-29 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_posts_options_posts_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dateposted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
